using Admin.ViewModel.Event;
using Admin.ViewModel.News;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.News;

public class NewsDetailsPanelView(NewsDetailsPanelViewModel viewModel) : UiView<NewsDetailsPanelViewModel>
{
    const int SizeRow = 5;

    public override IBuilder CreateUi(BuilderLayoutPanel layout)
    => layout.Column()
            .Row()
                .Column(45)
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Название: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите название")
                            .Binding(viewModel, nameof(viewModel.Title))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Дата:")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("dd.MM.yyyy")
                            .Binding(viewModel, nameof(viewModel.Date))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Категория: ")
                        .End()
                        .Column(40).Content()
                            .ComboBox()
                            .SetData(viewModel.CategoryEntities)
                            .Binding(viewModel, nameof(viewModel.Category))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Автор: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите имя автора")
                            .Binding(viewModel, nameof(viewModel.Author))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row()
                        .Column(10).Content()
                            .Label("Описание: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите описание")
                            .Binding(viewModel, nameof(viewModel.Description))
                            .Multiline()
                        .End()
                        .ColumnAbsolute(30).End()
                    .End()
                .End()
                .ColumnAbsolute(30)
                .End()
                .Column(55).Content()
                    .ImageLayoutPanel()
                    .CommandToggleImage(viewModel.ToggleImage)
                    .Binding(viewModel, nameof(viewModel.Images))
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Обновить")
                    .Command(viewModel.Update)
                .End()
                .Column().Content()
                    .Button("Добавить изображения")
                    .Command(viewModel.AddImages)
                .End()
                .Column().Content()
                    .Button("Удалить изображения")
                    .Command(viewModel.RemoveImages)
                .End()
                .Column().Content()
                    .Button("Удалить")
                    .Command(viewModel.Delete)
                .End()
            .End();
}