using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;
using Visitor.ViewModel.Visitor;

namespace Visitor.View.Visitor;

public class VisitorProfelPanelView(VisitorProfelPanelViewModel viewModel) : UiView<VisitorProfelPanelViewModel>
{
    public override IBuilder CreateUi(BuilderLayoutPanel builderLayoutPanel)
        => builderLayoutPanel.Column()
            .Row(30)
                .ColumnAutoSize().Content()
                    .Image()
                    .Binding(viewModel, nameof(viewModel.Image))
                .End()
                .Column()
                    .RowAbsolute(40).Content()
                        .Label(viewModel.FIO)
                        .Size(14)
                        .BorderStyle(BorderStyle.FixedSingle)
                    .End()
                    .RowAbsolute(40).Content()
                        .Label(viewModel.DateBurth)
                        .Size(14)
                        .BorderStyle(BorderStyle.FixedSingle)
                    .End()
                    .RowAbsolute(40).Content()
                        .Label(viewModel.NumberPhone)
                        .Size(14)
                        .BorderStyle(BorderStyle.FixedSingle)
                    .End()
                    .Row()
                    .End()
                .End()
                .Column().End()
            .End()
            .Row(70).Content()
                .DataGridView()
                .SetColumn("Уроки")
                .SetColumn(viewModel.GetDateAttendance())
                .SetRow(viewModel.GetAttendace())
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
            .End();
}
