using Admin.ViewModel.Model.Teacher;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Teacher;

public class TeacherDetailsPanelView(TeacherDetailsPanelViewModel viewModel) : UiView<TeacherDetailsPanelViewModel>
{
    const int SizeRow = 5;

    public override IBuilder CreateUi(BuilderLayoutPanel layout)
        => layout.Column()
             .Row()
                .Column()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Имя: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите имя")
                            .Binding(viewModel, nameof(viewModel.Name))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Фамилия: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите фамилию")
                            .Binding(viewModel, nameof(viewModel.Surname))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Отчество: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите отчество (если имеется)")
                            .Binding(viewModel, nameof(viewModel.Patronymic))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Дата рождения: ")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("dd.MM.yyyy")
                            .Binding(viewModel, nameof(viewModel.DateBirth))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Номер телефона: ")
                        .End()
                        .Column(40).Content()
                            .MaskedTextBox("+7 (000)-000-00-00")
                            .Binding(viewModel, nameof(viewModel.NumberPhone))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row().End()
                .End()
                .ColumnAutoSize().Content()
                     .Image(viewModel.Image)
                     .Change(url => viewModel.Image = url)
                     .ErrorMessage(viewModel, nameof(viewModel.Image))
                .End()
                .Column().Content()
                    .DataGridView()
                    .AddColumn("Название")
                    .AddColumn("Место проведения")
                    .Data(viewModel.GetDataGridLesson())
                .End()
             .End()
             .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Обновить")
                    .Command(viewModel.Update)
                .End()
                .Column().Content()
                    .Button("Удалить")
                    .Command(viewModel.Delete)
                .End()
                .Column().Content()
                    .Button()
                .End()
            .End();
}