using Teacher.ViewModel.Event;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Teacher.View.Event;

public class EventPanelView(EventPanelViewModel viewModel) : UiView<EventPanelViewModel>
{
    public override IBuilder CreateUi(BuilderLayoutPanel builderLayoutPanel)
    {
        return builderLayoutPanel.Column()
            .Row()
                .Column(20)
                    .RowAutoSize().Content()
                        .Label(viewModel.Title)
                        .Size(18)
                        .Alignment(ContentAlignment.TopCenter)
                        .ForeColor(Color.DarkBlue)
                    .End()
                    .RowAutoSize().Content()
                        .Label("Категория: " + viewModel.Category)
                        .ForeColor(Color.Black)
                        .Size(12)
                    .End()
                    .RowAutoSize().Content()
                        .Label("Локация: " + viewModel.Location)
                        .ForeColor(Color.Black)
                        .Size(12)
                    .End()
                    .RowAutoSize().Content()
                        .Label("Организатор: " + viewModel.Organizer)
                        .ForeColor(Color.Black)
                        .Size(12)
                    .End()
                    .RowAutoSize().Content()
                        .Label("Дата и время проведелния: " + viewModel.Schedule)
                        .Size(12)
                    .End()
                    .RowAbsolute(40)
                    .End()
                    .Row().Content()
                        .TextBox(viewModel.Description)
                        .Multiline()
                        .ReadOnly()
                        .Size(12)
                    .End()
                .End()
                .Column(40).Content()
                    .ImageLayoutPanel()
                    .Binding(viewModel, nameof(viewModel.Images))
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Регистрация")
                    .Command(viewModel.OpenLinkRegistration)
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
            .End();
    }
}