// <auto-generated />
using System.Collections.Generic;
using DataAccess.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319183837_test4")]
    partial class test4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.EventModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("UrlTitleImagId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "DataAccess.PostgreSQL.Models.EventModel.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "DataAccess.PostgreSQL.Models.EventModel.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Organizer", "DataAccess.PostgreSQL.Models.EventModel.Organizer#Organizer", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RegistrationLink", "DataAccess.PostgreSQL.Models.EventModel.RegistrationLink#Url", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "DataAccess.PostgreSQL.Models.EventModel.Schedule#EventSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "DataAccess.PostgreSQL.Models.EventModel.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UrlTitleImagId");

                    b.ToTable("EventModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.NewsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Author", "DataAccess.PostgreSQL.Models.NewsModel.Author#Author", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Date", "DataAccess.PostgreSQL.Models.NewsModel.Date#Date", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Description", "DataAccess.PostgreSQL.Models.NewsModel.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "DataAccess.PostgreSQL.Models.NewsModel.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("NewsModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasDiscriminator().HasValue("Image");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageEvent", b =>
                {
                    b.HasBaseType("DataAccess.PostgreSQL.Models.PropertyModel.Image");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.HasIndex("EntityId");

                    b.HasDiscriminator().HasValue("ImageEvent");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageNews", b =>
                {
                    b.HasBaseType("DataAccess.PostgreSQL.Models.PropertyModel.Image");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.HasIndex("EntityId");

                    b.ToTable("Image", t =>
                        {
                            t.Property("EntityId")
                                .HasColumnName("ImageNews_EntityId");
                        });

                    b.HasDiscriminator().HasValue("ImageNews");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.EventModel", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.PostgreSQL.Models.PropertyModel.Image", "UrlTitleImag")
                        .WithMany()
                        .HasForeignKey("UrlTitleImagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UrlTitleImag");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.NewsModel", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageEvent", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.Models.EventModel", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageNews", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.Models.NewsModel", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });
#pragma warning restore 612, 618
        }
    }
}
