// <auto-generated />
using System.Collections.Generic;
using DataAccess.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319185641_test9")]
    partial class test9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.EventModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "DataAccess.PostgreSQL.Models.EventModel.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "DataAccess.PostgreSQL.Models.EventModel.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Organizer", "DataAccess.PostgreSQL.Models.EventModel.Organizer#Organizer", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RegistrationLink", "DataAccess.PostgreSQL.Models.EventModel.RegistrationLink#Url", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "DataAccess.PostgreSQL.Models.EventModel.Schedule#EventSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Date")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "DataAccess.PostgreSQL.Models.EventModel.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UrlTitleImag", "DataAccess.PostgreSQL.Models.EventModel.UrlTitleImag#Image", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("EventModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.NewsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Author", "DataAccess.PostgreSQL.Models.NewsModel.Author#Author", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Date", "DataAccess.PostgreSQL.Models.NewsModel.Date#Date", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Description", "DataAccess.PostgreSQL.Models.NewsModel.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "DataAccess.PostgreSQL.Models.NewsModel.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("NewsModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EventModelId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Image", "DataAccess.PostgreSQL.Models.PropertyModel.ImageEvent.Image#Image", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.ToTable("ImagesEventModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageNews", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("NewsModelId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Image", "DataAccess.PostgreSQL.Models.PropertyModel.ImageNews.Image#Image", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("NewsModelId");

                    b.ToTable("ImagesNewsModels");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.EventModel", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.NewsModel", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.ModelsPrimitive.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageEvent", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.Models.EventModel", null)
                        .WithMany("Images")
                        .HasForeignKey("EventModelId");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.PropertyModel.ImageNews", b =>
                {
                    b.HasOne("DataAccess.PostgreSQL.Models.NewsModel", null)
                        .WithMany("Images")
                        .HasForeignKey("NewsModelId");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.EventModel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.PostgreSQL.Models.NewsModel", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
