// <auto-generated />
using System.Collections.Generic;
using DataAccess.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320182720_test11")]
    partial class test11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.CategoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.ComplexProperty<Dictionary<string, object>>("Category", "Domain.Models.CategoryModel.Category#CategoryP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("CategoryModel");
                });

            modelBuilder.Entity("Domain.Models.EventModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Domain.Models.EventModel.Description#DescriptionP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "Domain.Models.EventModel.Location#LocationP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Organizer", "Domain.Models.EventModel.Organizer#OrganizerP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RegistrationLink", "Domain.Models.EventModel.RegistrationLink#UrlP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "Domain.Models.EventModel.Schedule#EventScheduleP", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Date", "Domain.Models.EventModel.Schedule#EventScheduleP.Date#DateP", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("End", "Domain.Models.EventModel.Schedule#EventScheduleP.End#TimeP", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Start", "Domain.Models.EventModel.Schedule#EventScheduleP.Start#TimeP", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "Domain.Models.EventModel.Title#TitleP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UrlTitleImag", "Domain.Models.EventModel.UrlTitleImag#ImageP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("EventModels");
                });

            modelBuilder.Entity("Domain.Models.ImageEventModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EventModelId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("ImageP", "Domain.Models.ImageEventModel.ImageP#ImageP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.ToTable("ImageEventModel");
                });

            modelBuilder.Entity("Domain.Models.ImageNewsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("NewsModelId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("ImageP", "Domain.Models.ImageNewsModel.ImageP#ImageP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("NewsModelId");

                    b.ToTable("ImageNewsModel");
                });

            modelBuilder.Entity("Domain.Models.NewsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.ComplexProperty<Dictionary<string, object>>("Author", "Domain.Models.NewsModel.Author#Author", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Date", "Domain.Models.NewsModel.Date#DateP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DescriptionP", "Domain.Models.NewsModel.DescriptionP#DescriptionP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TitleP", "Domain.Models.NewsModel.TitleP#TitleP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("NewsModels");
                });

            modelBuilder.Entity("Domain.Models.EventModel", b =>
                {
                    b.HasOne("Domain.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.ImageEventModel", b =>
                {
                    b.HasOne("Domain.Models.EventModel", null)
                        .WithMany("Images")
                        .HasForeignKey("EventModelId");
                });

            modelBuilder.Entity("Domain.Models.ImageNewsModel", b =>
                {
                    b.HasOne("Domain.Models.NewsModel", null)
                        .WithMany("Images")
                        .HasForeignKey("NewsModelId");
                });

            modelBuilder.Entity("Domain.Models.NewsModel", b =>
                {
                    b.HasOne("Domain.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.EventModel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Models.NewsModel", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
