using Admin.ViewModel.Model.Visitor;
using Domain.Entitys;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Visitor;

public class VisitorManagerPanelView(VisitorManagerPanelViewModel viewModel) : UiView<VisitorManagerPanelViewModel>
{
    public override IBuilder CreateUi(BuilderLayoutPanel layout)
        => layout.Column()
            .Row()
                .Column(80).Content()
                    .CardFlowLayoutPanel<VisitorEntity, VisitorCard>()
                    .ClickedCard(viewModel.LoadDetailsPanel)
                    .Binding(viewModel, nameof(viewModel.VisitorEntities))
                .End()
                .Column(20).Content()
                .Panel()
                .Contents(b => 
                    b.Column()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Имя: ")
                            .End()
                            .Column().Content()
                                .TextBox()
                                .Binding(viewModel, nameof(viewModel.Name))
                            .End()
                        .End()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Фамилия: ")
                            .End()
                            .Column().Content()
                                .TextBox()
                                .Binding(viewModel, nameof(viewModel.Surname))
                            .End()
                        .End()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("c: ")
                            .End()
                            .Column().Content()
                                .Numeric()
                                .Binding(viewModel, nameof(viewModel.StartYear))
                            .End()
                            .Column().Content()
                                .Label("по: ")
                            .End()
                            .Column().Content()
                                .Numeric()
                                .Binding(viewModel, nameof(viewModel.EndYear))
                            .End()
                        .End()
                        .Row()
                        .End()
                        .RowAbsolute(60).Content()
                            .Button("Очистить")
                            .Command(viewModel.ClearSearch)
                        .End()
                )
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
            .End();
}