<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="Ninject.Extensions.Conventions" Version="3.3.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BCrypt.Net-Next">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\BCrypt.Net-Next.dll</HintPath>
    </Reference>
    <Reference Include="CSharpFunctionalExtensions">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\CSharpFunctionalExtensions.dll</HintPath>
    </Reference>
    <Reference Include="DataAccess.PostgreSQL">
      <HintPath>..\..\DataAccess.PostgreSQL\bin\Debug\net8.0\DataAccess.PostgreSQL.dll</HintPath>
    </Reference>
    <Reference Include="Domain">
      <HintPath>..\..\DataAccess.PostgreSQL\bin\Debug\net8.0\Domain.dll</HintPath>
    </Reference>
    <Reference Include="General">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\General.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Abstractions">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Microsoft.EntityFrameworkCore.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="Ninject">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Ninject.dll</HintPath>
    </Reference>
    <Reference Include="Ninject.Extensions.Conventions">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Ninject.Extensions.Conventions.dll</HintPath>
    </Reference>
    <Reference Include="Ninject.Extensions.Factory">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\Ninject.Extensions.Factory.dll</HintPath>
    </Reference>
    <Reference Include="UserInterface">
      <HintPath>..\..\VisitorPanel\Visitor\bin\Debug\net8.0-windows\UserInterface.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>