using Admin.ViewModel.Model.Lesson;
using Domain.Entitys;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Lesson;

public class LessonManagerPanelView(LessonManagerPanelViewModel viewModel) : UiView<LessonManagerPanelViewModel>
{
    public override IBuilder CreateUi(BuilderLayoutPanel layout)
    {
        return layout.Column()
            .Row()
                .Column(75).Content()
                    .CardFlowLayoutPanel<LessonEntity, LessonCard>()
                    .ClickedCard(viewModel.LoadDetailsPanel)
                    .ContextMenu("Управление поситителями", viewModel.ControlVisitors)
                    .ContextMenu("Управление посищаемостью", viewModel.ControlDateAttendance)
                    .ContextMenu("Управление отзывами", viewModel.ControlReview)
                    .Binding(viewModel, nameof(viewModel.Learches))
                .End()
                .Column(25).Content()
                    .Panel()
                    .Contents(build => build.Column()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Категория: ")
                            .End()
                            .Column().Content()
                                .ComboBox()
                                .SetData(viewModel.CategoryEntities)
                                .Binding(viewModel, nameof(viewModel.Category))
                            .End()
                        .End()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Название: ")
                            .End()
                            .Column().Content()
                                .TextBox()
                                .Binding(viewModel, nameof(viewModel.Title))
                            .End()
                        .End()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Имя преподователя: ")
                            .End()
                            .Column().Content()
                                .TextBox()
                                .Binding(viewModel, nameof(viewModel.TeacherName))
                            .End()
                        .End()
                        .RowAbsolute(40)
                            .Column().Content()
                                .Label("Фамилия преподователя: ")
                            .End()
                            .Column().Content()
                                .TextBox()
                                .Binding(viewModel, nameof(viewModel.TeacherSurname))
                            .End()
                        .End()
                        .Row()
                        .End()
                        .RowAbsolute(80).Content()
                            .Button("Очитить поиск")
                            .Command(viewModel.ClearSearch)
                        .End()
            )
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Добавить")
                    .Command(viewModel.LoadAddingPanel)
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
            .End();
    }
}