using Admin.ViewModel.Model.Lesson;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Lesson;

public class LessonDetailsPanelView(LessonDetailsPanelViewModel viewModel) : UiView<LessonDetailsPanelViewModel>
{
    const int SizeRow = 5;

    public override IBuilder CreateUi(BuilderLayoutPanel layout)
    {
        return layout.Column()
           .Row()
               .Column()
                   .Row(SizeRow)
                       .Column(10).Content()
                           .Label("Название: ")
                       .End()
                       .Column(40).Content()
                           .TextBox("Введите название")
                           .Binding(viewModel, nameof(viewModel.Title))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
                   .Row(SizeRow)
                       .Column(10).Content()
                           .Label("Место проведения: ")
                       .End()
                       .Column(40).Content()
                           .TextBox("Введите место проведения")
                           .Binding(viewModel, nameof(viewModel.Location))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
                   .Row(SizeRow)
                       .Column(10).Content()
                           .Label("Кол. участников: ")
                       .End()
                       .Column(40).Content()
                           .Numeric()
                           .Binding(viewModel, nameof(viewModel.MaxParticipants))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
                   .Row(SizeRow)
                       .Column(10).Content()
                           .Label("Категория: ")
                       .End()
                       .Column(40).Content()
                           .ComboBox()
                           .SetData(viewModel.CategoryEntities)
                           .Binding(viewModel, nameof(viewModel.Category))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
                   .Row(SizeRow)
                       .Column(10).Content()
                           .Label("Преподователь: ")
                       .End()
                       .Column(40).Content()
                           .ComboBox()
                           .SetData(viewModel.TeacherEntities)
                           .Binding(viewModel, nameof(viewModel.Teacher))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
                   .Row()
                       .Column(10).Content()
                           .Label("Описание: ")
                       .End()
                       .Column(40).Content()
                           .TextBox("Введите описание")
                           .Multiline()
                           .Binding(viewModel, nameof(viewModel.Description))
                       .End()
                       .Column(30, SizeType.Absolute)
                       .End()
                   .End()
               .End()
               .Column().Content()
                   .ImageLayoutPanel()
                   .Binding(viewModel, nameof(viewModel.Images))
               .End()
           .End()
           .RowAbsolute(80)
               .Column().Content()
                   .Button("Назад")
                   .Command(viewModel.Exit)
               .End()
               .Column().Content()
                   .Button("Обновить")
                   .Command(viewModel.Update)
               .End()
               .Column().Content()
                   .Button("Расписание")
                   .Command(viewModel.Schedule)
               .End()
               .Column().Content()
                   .Button("Добавить изображение")
                   .Command(viewModel.AddImages)
               .End()
               .Column().Content()
                   .Button("Удалить изображение")
                   .Command(viewModel.RemoveImages)
               .End()
           .End();
    }
}