using Admin.ViewModel.Model.Event;
using Domain.Entitys;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Event;

public class EventManagerPanelView(EventManagerPanelViewModel viewModel) : UiView<EventManagerPanelViewModel>
{
    public override IBuilder CreateUi(BuilderLayoutPanel layout)
        => layout.Column()
            .Row()
                .Column(80).Content()
                    .CardFlowLayoutPanel<EventEntity, EventCard>()
                    .ClickedCard(viewModel.LoadDetailsPanel)
                    .Binding(viewModel, nameof(viewModel.EventsEntities))
                .End()
                .Column(20).Content()
                    .Panel()
                    .Contents(b => 
                        b.Column()
                            .RowAbsolute(40)
                                .Column().Content()
                                    .Label("Категория: ")
                                .End()
                                .Column().Content()
                                    .ComboBox()
                                    .SetData(viewModel.CategoryEntities)
                                    .Binding(viewModel, nameof(viewModel.Category))
                                .End()
                            .End()
                            .RowAbsolute(40)
                                .Column().Content()
                                    .Label("Название: ")
                                .End()
                                .Column().Content()
                                    .TextBox()
                                    .Binding(viewModel, nameof(viewModel.Title))
                                .End()
                            .End()
                            .RowAbsolute(40)
                                .Column().Content()
                                    .Label("c: ")
                                .End()
                                .Column().Content()
                                    .MaskedTextBox("00/00/0000")
                                    .Binding(viewModel, nameof(viewModel.StartDate))
                                .End()
                            .End()
                            .RowAbsolute(40)
                                .Column().Content()
                                    .Label("по: ")
                                .End()
                                .Column().Content()
                                    .MaskedTextBox("00/00/0000")
                                    .Binding(viewModel, nameof(viewModel.EndDate))
                                .End()
                            .End()
                            .Row()
                            .End()
                            .RowAbsolute(60).Content()
                                .Button("Очистить")
                                .Command(viewModel.ClearSearch)
                            .End()
                        )
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Добавить")
                    .Command(viewModel.LoadAddingPanel)
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
                .Column().Content()
                    .Button()
                    .NoEnable()
                .End()
            .End();
}