using Abstract.View;
using AbstractView.View;
using Domain.Command;
using Domain.Entitys;
using Domain.Repository;
using System.Windows.Input;
using Admin.ViewModel.Model.Event;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;

namespace Admin.View.Moduls.Event;

public class EventAddingPanelView(
    EventViewModel viewModel, 
    ControlView controlView, 
    IRepository<CategoryEntity> repositoryC) : UiView
{
    private readonly ICommand _exit = new ExecuteCommand(_ => controlView.Exit());

    const int SizeRow = 5;
    protected override IBuilder CreateUi(BuilderLayoutPanel layout)
    {
        return layout.Column()
            .Row()
                .Column()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Название: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите название")
                            .Binding(viewModel, nameof(viewModel.Title))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Главное изображение: ")
                        .End()
                        .ColumnAutoSize().Content()
                            .Image()
                            .Binding(viewModel, nameof(viewModel.TitleImg))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Дата:")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("dd.MM.yyyy")
                            .Binding(viewModel, nameof(viewModel.Date))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Начало: ")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("HH:mm")
                            .Binding(viewModel, nameof(viewModel.TimeStart))
                            .MessageError(viewModel, nameof(viewModel.Schedule))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Конец: ")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("HH:mm")
                            .Binding(viewModel, nameof(viewModel.TimeEnd))
                            .MessageError(viewModel, nameof(viewModel.Schedule))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Категория: ")
                        .End()
                        .Column(40).Content()
                            .ComboBox()
                            .SetData(repositoryC.Get().ToArray())
                            .Binding(viewModel, nameof(viewModel.Category))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Место: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите место проведения")
                            .Binding(viewModel, nameof(viewModel.Location))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Ссылка на регистрацию: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите ссылку на регистрацию")
                            .Binding(viewModel, nameof(viewModel.RegisLink))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Организатор: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите название организации")
                            .Binding(viewModel, nameof(viewModel.Organizer))
                        .End()
                        .Column(30, SizeType.Absolute)
                        .End()
                    .End()
                    .Row(80)
                        .Column(10).Content()
                            .Label("Описание: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите описание")
                            .Binding(viewModel, nameof(viewModel.Description))
                            .Multiline()
                        .End()
                        .Column(30, SizeType.Absolute).End()
                    .End()
                .End()
            //.Column()
            //    .RowAutoSize().Content().Label("📷 Изображения:").End()
            //    .Row().ContentEnd(new ImageLayoutPanel(DataUi.RepositoryImgEntity))
            //.End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(_exit)
                .End()
                .Column().Content()
                    .Button("Добавить")
                    .Command(viewModel.Save)
                .End()
            .End();
    }
}