using Admin.ViewModel.Model.Event;
using UserInterface.LayoutPanel;
using UserInterface.LayoutPanel.Extension;
using UserInterface.View;

namespace Admin.View.Moduls.Event;

public class EventAddingPanelView(EventAddingPanelViewModel viewModel) : UiView<EventAddingPanelViewModel>
{
    const int SizeRow = 7;

    public override IBuilder CreateUi(BuilderLayoutPanel layout)
    {
        return layout.Column()
            .Row()
                .Column()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Название: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите название")
                            .Binding(viewModel, nameof(viewModel.Title))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Дата:")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("dd.MM.yyyy")
                            .Binding(viewModel, nameof(viewModel.Date))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Начало: ")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("HH:mm")
                            .Binding(viewModel, nameof(viewModel.TimeStart))
                            .MessageError(viewModel, nameof(viewModel.Schedule))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Конец: ")
                        .End()
                        .Column(40).Content()
                            .DateTimePicker("HH:mm")
                            .Binding(viewModel, nameof(viewModel.TimeEnd))
                            .MessageError(viewModel, nameof(viewModel.Schedule))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Категория: ")
                        .End()
                        .Column(40).Content()
                            .ComboBox()
                            .SetData(viewModel.CategoryEntities)
                            .Binding(viewModel, nameof(viewModel.Category))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Место: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите место проведения")
                            .Binding(viewModel, nameof(viewModel.Location))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Ссылка на регистрацию: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите ссылку на регистрацию")
                            .Binding(viewModel, nameof(viewModel.RegisLink))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row(SizeRow)
                        .Column(10).Content()
                            .Label("Организатор: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите название организации")
                            .Binding(viewModel, nameof(viewModel.Organizer))
                        .End()
                        .ColumnAbsolute(30)
                        .End()
                    .End()
                    .Row()
                        .Column(10).Content()
                            .Label("Описание: ")
                        .End()
                        .Column(40).Content()
                            .TextBox("Введите описание")
                            .Binding(viewModel, nameof(viewModel.Description))
                            .Multiline()
                        .End()
                        .ColumnAbsolute(30).End()
                    .End()
                .End()
                .ColumnAutoSize().Content()
                    .Image()
                    .Change(url => viewModel.TitleImg = url)
                    .ErrorMessage(viewModel, nameof(viewModel.TitleImg))
                .End()
                .ColumnAbsolute(30)
                .End()
                .Column().Content()
                    .ImageLayoutPanel()
                    .Setting(
                        viewModel.ServiceImage.GetImages(),
                        viewModel.ServiceImage.ToggleImage(),
                        viewModel.ServiceImage.SetAction)
                .End()
            .End()
            .RowAbsolute(80)
                .Column().Content()
                    .Button("Назад")
                    .Command(viewModel.Exit)
                .End()
                .Column().Content()
                    .Button("Добавить")
                    .Command(viewModel.Save)
                .End()
            .End();
    }
}